### ISSUE TITLE
Crash in production React app

### ISSUE THREAD

**Issue by OllieRushton** [placemark/togeojson#44]
Hello @tmcw !

We're currently using v4.3.0 (also tested in v4.2.0) of togeojson.

When calling `tj.kml` with this [kml file ](https://pastebin.pl/view/e7415a32) in our React v16.12.0 production app, based on create-react-app, We get the following console error:

```
TypeError: u is not a function
    at kml.js:296
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at Function.from (<anonymous>)
    at e.kml (kml.js:316)
    at Object.KML (index.es.js:32035)
    at setTimeout.format (index.es.js:32063)
    at index.es.js:32225
```

This error does not occur when running locally in development, and when using your online tool, again there is no problems. Therefore we think the issue lies in the minified build.

Just to clarify, KML files without the StyleMap element do not have this problem.

I'd appreciate any assistance you could provide :)

Using as below:

```
  import * as toGeoJSON from '@tmcw/togeojson';

  ...

  const dom = (new DOMParser()).parseFromString(kmlString, 'text/xml');
  const parsedGeojson = toGeoJSON.kml(dom);
```

**Comment by tmcw** [comment]
Could you try and get a better error report? It's pretty difficult to debug anything based on only a minified traceback. Try:

- When you get this, click on the source line after the crash, `kml.js:296`
- If that looks garbled, try clicking on the `{}` icon to format the minified source
- Share that code context. Also maybe check the `kml:316` line to see where that part of the stacktrace is.

**Comment by OllieRushton** [comment]
So the console error In the previous post is using the modules source map to print a stack trace with the un-minified code. 

So when it refers to line `at kml.js:296` and `at e.kml (kml.js:316)`, it's actually refering to your source code at those lines:

https://github.com/tmcw/togeojson/blob/8e007333a512e2cd6f6df182a3a9768cfdf55abd/lib/kml.js#L296

https://github.com/tmcw/togeojson/blob/8e007333a512e2cd6f6df182a3a9768cfdf55abd/lib/kml.js#L316

After debugging in the console, I found that what should have been the var storing the function `nodeVal`, seems to get overwritten with a style hash, which would explain the error `TypeError: u is not a function`. How that happens, I have no clue.

Looking at the Closure for `kmlGen` which gives us the minified variable names:

```
l: HTMLCollection(1)
  0: stylemap#__managed_style_0E9F304A601813AF2709
  length: 1
  __managed_style_0E9F304A601813AF2709: stylemap#__managed_style_0E9F304A601813AF2709
  __proto__: HTMLCollection
n: HTMLCollection(2)
  0: pair
  1: pair
  length: 2
  __proto__: HTMLCollection
o: {}
r: {}
s: HTMLCollection(2)
  0: style
  1: style
  length: 2
  __proto__: HTMLCollection
t:
  #__managed_style_0E9F304A601813AF2709: "4eb927af"
  #null: "-2415b9bd"
  __proto__: Object
u: "-2415b9bd" // <-- This seems to have the value of the last style hash to be computed,
```

Where the variable names here map to:

* l: styleMaps,
* n: pairs,
* o: pairsMap,
* r: styleByHash,
* s: styles,
* t: styleIndex,
* u: probably the last style hash

however, in the minified code, we're calling `u` like its the function for `nodeVal`:

```
// minified
296  o[u(c(n[e], "key"))] = ...

// normal
296  pairsMap[nodeVal(get1(pairs[m], "key"))] = ...
```

Also, ran a build with my webpack config using the `optimization: { minimize: false }` flag set, and I don't get the error anymore, so it's only an issue in the minified code.

Here's the minified code for the kmlGen function:
```
function R(e) {
  var t, n, r, o, s, l, u;
  return i.wrap((function(i) {
    for (;;) switch (i.prev = i.next) {
      case 0:
        for (t = {}, n = {}, r = {}, o = e.getElementsByTagName("Placemark"), s = e.getElementsByTagName("Style"), l = e.getElementsByTagName("StyleMap"), e = 0; e < s.length; e++) u = T(P(s[e])).toString(16), t["#" + s[e].getAttribute("id")] = u, n[u] = s[e];
        for (e = 0; e < l.length; e++) {
          for (t["#" + l[e].getAttribute("id")] = T(P(l[e])).toString(16), n = l[e].getElementsByTagName("Pair"), o = {}, e = 0; e < n.length; e++) o[u(c(n[e], "key"))] = u(c(n[e], "styleUrl"));
          r["#" + l[e].getAttribute("id")] = o
        }
        e = 0;
      case 4:
        if (!(e < o.length)) {
          i.next = 13;
          break
        }
        if (u = k(o[e], t, r, n), i.t0 = u, !i.t0) {
          i.next = 10;
          break
        }
        return i.next = 10, u;
      case 10:
        e++, i.next = 4;
        break;
      case 13:
      case "end":
        return i.stop()
    }
  }), a)
}
```

Also we're using Terser as our minifier

Let me know if you need anything else :)
